site_name: Raconteur User Documentation
theme: readthedocs
pages:
  - ['index.md', 'Introduction', 'What is Raconteur?']
  - ['philosophy.md', 'Introduction', 'Design Philosophy']
  - ['situation.md', 'API Documentation', 'situation.js']
  - ['elements.md', 'API Documentation', 'elements.js']
  - ['oneOf.md', 'API Documentation', 'oneOf.js']
  - ['qualities.md', 'API Documentation', 'qualities.js']
